# Generated by Django 3.1.7 on 2021-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
